### ISSUE TITLE
Error in parseGeneral: e.achivements.int is not iterable

### ISSUE THREAD

**Issue by Draksis45** [communitycenter/stardew.app#110]
Version 1.6.8 Build 24119

Error when uploading save file: Error in parseGeneral: e.achivements.int is not iterable
![Error](https://github.com/communitycenter/stardew.app/assets/38989730/dd583793-7a54-4e5e-a2d3-e228cc0ce19b)

**Comment by jacc** [comment]
Can you upload your save file?

**Comment by Draksis45** [comment]
[BreezeValley_370612942.zip](https://github.com/communitycenter/stardew.app/files/15267433/BreezeValley_370612942.zip)

**Comment by Esummins** [comment]
@Draksis45 should be fixed in the most recent update. Thanks for the savefile 👍
