### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [communitycenter/stardew.app#54]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by clxmente** [comment]
Bit of an oversight on our part, I thought we already had a license on the project 😅. I think I'll first have to remove and gitignore the raw game files in `src/research/raw_data` and then we should be good to add a permissive license like MIT.

@jacc

**Comment by SkyBulk** [comment]
sure, thanks.
