### ISSUE TITLE
Manual updates to monster slayer goals don't save

### ISSUE THREAD

**Issue by Terrance** [communitycenter/stardew.app#57]
When submitting an updated count for a monster slayer goal, the page just reloads instead of saving the value.  This happens for both the main farmer and any farmhands on a co-op save (with the page always reverting to the main farmer's stats).

**Comment by clxmente** [comment]
I just tried it out right now and it looks the values are correctly updating 🤔

It looks like there is some weird behavior though as the page should definitely not refresh when changing those values. After updating a value and the page refreshes, it switches the current player to the main farmhand, but the values correctly update for any co-op farmhands I try and change as well. Can you confirm this?

Regardless, the page refresh is certainly a bug so thank you for pointing this out! We'll try and fix it as soon as possible

**Comment by Terrance** [comment]
I've tried both characters and neither seem to save.  Looking in the browser console, it seems like the PATCH request for the save file is aborted (presumably because of the reload) so the change just doesn't make it to the server?

**Comment by clxmente** [comment]
That makes sense. Could depend on our internet speeds / how close or far we are to the server which would explain why it works for me and not for you 

Looks like @jacc didn't handle the form submit in the component so it triggers a refresh. Should be a quick fix 😁

**Comment by dannykd** [comment]
@jacc fixed it heheeheheeh

**Comment by Terrance** [comment]
Can confirm that's now working, thanks!
