### ISSUE TITLE
"Upgrade Required" on local build

### ISSUE THREAD

**Issue by Terrance** [communitycenter/stardew.app#58]
I had a go and running the site locally, but with either of the dev (`npm run dev`) or prod (`npm run build && npm run start`) servers, I end up with a blank page and just the text `Upgrade Required` (along with the corresponding HTTP status code):

![image](https://github.com/communitycenter/stardew.app/assets/4025899/614700e3-5b89-476a-a205-a3c98e2474b8)

Unfortunately I'm not familiar with Next.js and this error doesn't seem to be very searchable, so I'm not sure if there's a problem with my local setup (using Node.js 18 LTS which Next.js 13 [seemingly supports](https://nextjs.org/docs/pages/building-your-application/upgrading/version-13)) or how I'm starting the app -- is there a step I'm missing here?

**Comment by clxmente** [comment]
Unfortunately, I have not been able to reproduce this on my machine. I have tried re-cloning the repo into a new directory and using Node v18.8.2 was still able to successfully start a local dev server. It worked on the 3 browsers I tested (Chrome, Firefox, and Edge). Here is an example:

![image](https://github.com/communitycenter/stardew.app/assets/37494038/efd15c54-4428-434b-bb29-d69cbf73c7dc)

Is there any information in the 426 Response to indicate what the issue might be? [The MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426) show an example of what the message might look like:

```
HTTP/1.1 426 Upgrade Required
Upgrade: HTTP/2.0
Connection: Upgrade
Content-Length: 53
Content-Type: text/plain

This service requires use of the HTTP/2.0 protocol
```

**Comment by Terrance** [comment]
Ok, looks like this is specific to Windows (or at least WSL) -- port 3000 is bound by an identifiable (presumably system) process on the native side, so I can access the server within WSL (e.g. via curl) but the automatic port forwarding clashes.  I'm to assume the `Upgrade Required` response is just coming from whatever websocket service is using that port.

Running with `npm run dev -- -p 8000` to use an alternative port seems to work fine.
