### ISSUE TITLE
Legendary Fish have incorrect seasons

### ISSUE THREAD

**Issue by tindolt** [communitycenter/stardew.app#62]
Angler has incorrect season tags

**Comment by clxmente** [comment]
This actually an issue for all legendary fish. We use the data from the game files on fish, but looking at the source code the legendary fish are hardcoded into certain locations and conditions so I think we'll have to do the same.

**Comment by tindolt** [comment]
I was noticing that. Maybe a special tag attached to those fish as legendary or something or manually remove the other seasons where they can't be caught. I'll look at the code myself and see if I can come up with a working solution and make a branch on this issue to merge.

**Comment by clxmente** [comment]
https://github.com/communitycenter/stardew.app/blob/7b821964f4638353b1531ddd0803cad05785aec1/src/research/processors/fish.py#L78

If you're interested this is the line causing the issue. There should be some extra checks here to handle the legendary fish and hardcode the seasons.

I should be able to fix this a bit later if you haven't done so already 👍

**Comment by tindolt** [comment]
For now I pulled the incorrect season data and updated it a tiny bit to offer it being correct. I will look into the fish.py stuff after so new json data can be grabbed without reverting previous changes made.

Also will be opening a PR for a bundles screen at some point in the future.
