### ISSUE TITLE
New item badge on Mastery card is blurred out

### ISSUE THREAD

**Issue by TheLostSoul** [communitycenter/stardew.app#70]
The 1.6 badge on the Mastery skill card is included in the new content blur.  Additionally choosing to show new content, causes a horizontal scrollbar on the page.

![image](https://github.com/communitycenter/stardew.app/assets/718358/b87a5df9-1717-4202-8b29-94339d24ac74)

**Comment by clxmente** [comment]
i think the mastery skill card is supposed to be blurred since it's new content but @jacc definitely broke something with the horizontal scroll bar 🤔🤔

**Comment by TheLostSoul** [comment]
Yeah, the card is supposed to be blurred, but not the badge in the top right.  As for the horizontal scrollbar, apparently the CSS blur filter creates a positioned element, because the card is not relative positioned, so the badge jumps to the top right of the page, hiding behind the sticky header once the blur is removed.  This extends the page just enough to create the scrollbar.

My PR addresses all of that.  I also added a position property to the badge because otherwise the badge on the Mastery card has no space from the above element, so it doesn't offset the badge that far.

**Comment by jacc** [comment]
This is such an incredible PR and handles a few things I was looking to get done this week - I also appreciate the future proofing on the NewItemBadge versioning. Thank you so much!
