### ISSUE TITLE
[STA-135] Selected farmhand doesn't persist across page refresh

### ISSUE THREAD

**Issue by jacc** [communitycenter/stardew.app#75]
With more than two farmhands, after selecting one, refreshing the page does not persist with the selected farmhand.

<sub>From [SyncLinear.com](https://synclinear.com) | [STA-135](https://linear.app/stardew/issue/STA-135/selected-farmhand-doesnt-persist-across-page-refresh)</sub>

**Comment by clxmente** [comment]
updated the logic in players-context, and added a local storage item which saves the last selected farmhand. If this local storage item is present, it sets the active player to that, if not it defaults to the first player in the players array as usual. Also deletes the local storage item if the character deletes the player, all players, or their account
